@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/List-AssignRef/project>
	deps:runtime-requirement         [ deps:on "LV"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Exporter::Shiny"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "List::MoreUtils"^^deps:CpanId ].

