# This file provides instructions for packaging.

`List-AssignRef`
	perl_version_from m`List::AssignRef`;
	version_from      m`List::AssignRef`;
	readme_from       m`List::AssignRef`;
	test_requires     p`Test::More 0.61`;
	test_requires     p`List::MoreUtils`;
	requires          p`lvalue`;
	requires          p`Sub::Exporter`;
.

